### ISSUE TITLE
[bug?] failed to load after install

### ISSUE THREAD

**Issue by zeltak** [alythobani/obsidian-callout-toggles#14]
Hi

tried to install and it did but it wont load and give a failed to load error

```
allout Toggles: styles.css not found
app.js:1 Plugin failure: callout-toggles TypeError: Cannot read properties of null (reading 'pluginVersion')
    at k.loadSettings (plugin:callout-toggles:1:17601)
    at async k.setupSettingsTab (plugin:callout-toggles:1:17481)
    at async j.onload (plugin:callout-toggles:1:21852)
```

cheers

Z

**Comment by alythobani** [comment]
Oops thanks for filing this! Just released v1.2.1 to fix this, hope it works now

**Comment by zeltak** [comment]
cool works well now!

thx for you epic work! :)

**Comment by alythobani** [comment]
Awesome great to hear! Aw no problem, happy this is useful to others. Thanks for the kind words :)
