### ISSUE TITLE
你这格式也太乱了

### ISSUE THREAD

**Issue by qiekqiek** [alythobani/obsidian-callout-toggles#4]
不好手动修改阿

**Comment by alythobani** [comment]
Hi @qiekqiek  thank you for your feedback!

In the future please file issues in English, with visual examples if possible, to help communication. I don't speak Chinese unfortunately (I wish I did).

But here is Google's translation of your feedback:

> Title: Your format is too messy. #4
> Body: It is not good to modify manually

My understanding is that this feedback is not relevant to this plugin. Callout syntax is defined by Obsidian itself, and not the Callout Toggles plugin. See Obsidian docs: https://help.obsidian.md/Editing+and+formatting/Callouts

I'll close this issue as unrelated. If I'm misunderstanding your feedback, please feel free to reply (in English) and I can reopen if appropriate.

Have a great day!
