### ISSUE TITLE
[FR] Make callouts foldable

### ISSUE THREAD

**Issue by VerAn1015** [alythobani/obsidian-callout-toggles#5]
Hi! Thank you for creating this useful plugin. As someone who uses callouts a lot, this speeds up my workflow significantly.

It would be great if commands to make the callouts foldable are also added since at the moment, I have to type the + or - sign manually. I believe this addition would certainly make the addition of callouts in my notes a more seamless experience.

Nonetheless, thank you so much once again!

**Comment by alythobani** [comment]
Hey @VerAn1015  thanks for the kind words, I'm glad to hear that :)

I can think of a couple approaches that involve adding commands:
1) Adding two commands like "Make current callout folded by default" and "Make current callout unfolded by default"
2) Adding two more commands for every callout type, thus three commands provided total per callout type: "Wrap lines in X callout (unfoldable)", "Wrap lines in X callout (folded)", "Wrap lines in X callout (unfolded)"

But I can also think of a simpler approach that just involves a dropdown setting instead, e.g.:

## Settings

### Foldable callouts

Newly inserted callouts should be:

_(Dropdown options)_
- [ ] Unfoldable (e.g. `> [!quote]`)
- [ ] Foldable, and expanded by default (e.g. `> [!quote]+`)
- [ ] Foldable, and collapsed by default (e.g. `> [!quote]-`)

---

How does that sound to you? I think it might be a nice balance of simplicity to implement and smoothness of UX (assuming you don't constantly need to toggle this setting).

**Comment by VerAn1015** [comment]
I agree with having it as a setting. It indeed is a simpler approach than having to constantly run the commands. I would love to see this implemented. Thank you for hearing this request! Very much appreciated.

**Comment by alythobani** [comment]
Great to hear! I'll get to implementing the setting when I have some free time :)

**Comment by alythobani** [comment]
Hey @VerAn1015 , I just released version `1.1.0` that implements this setting (plus a couple other related settings). Let me know if there are any issues with it, otherwise enjoy!
