### ISSUE TITLE
[FR] capitalize callout keyword

### ISSUE THREAD

**Issue by huyz** [alythobani/obsidian-callout-toggles#6]
I've been using Microsoft's convention of capitalizing the callout keyword:
- Microsoft: https://learn.microsoft.com/en-us/contribute/content/markdown-reference
- GitHub https://github.com/orgs/community/discussions/16925

For consistency with all my notes, can this be added as an option?

**Comment by alythobani** [comment]
Totally! I can get to this when I have time, or in the meantime I'm happy to accept a PR from you or anyone else that implements this as a setting :)

**Comment by alythobani** [comment]
Hey @huyz , I just released version `1.1.0` that implements this setting (plus a couple other related ones). Hope it's useful for you, and let me know if there are any issues :)

**Comment by huyz** [comment]
@alythobani Nice, thank you!
